[package]
name = "focal"
version = "0.1.0"
authors = ["iynaix"]

edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "string"] }
dirs = "5.0.1"
execute = "0.2.13"
regex = "1.11.0"
clap_complete = "4.5.33"
serde_json = "1.0.128"
serde = "1.0.210"
which = "6.0.3"
chrono = "0.4.38"
hyprland = { version = "0.4.0-alpha.3" }
serde_derive = "1.0.210"
notify-rust = "4.11.3"
ctrlc = "3.4.5"

[features]
default = ["hyprland", "ocr", "video"]
hyprland = []
sway = []
ocr = []
video = []

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
missing_errors_doc = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
must_use_candidate = { level = "allow", priority = 1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"

[profile.release]
strip = true
lto = true
