name: "Cachix Cache"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        package:
          - focal
          - focal-sway
          - focal-niri

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: focal
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#${{ matrix.package }}